name: Terraform CI


on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform Format, Init, Plan, and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # use your version here

      - name: Terraform Init
        run: terraform init


      - name: Terraform Plan
        run: terraform plan

      # Uncomment below only if you're ready to auto-apply changes
      - name: Terraform Apply
        run: terraform apply -auto-approve

